uploads = []
outputs = []

[[generated]]
id = "lGFUq7YP8uD0elA-fX45R"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NFcNfLD9lxtmA8YSI4P_B"
uri = "file://artifacts/mobile/public/icon-512.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r_duNVvXz7CZreaSas7yi"
uri = "file://artifacts/mobile/public/icon-192.png"
type = "image"
title = "generated_image"
